import { useI18n } from '../context/I18nContext';
import { useAuth } from '../context/AuthContext';
import { COLORS, RADIUS, SHADOW } from '../constants/theme';
import { createBooking, getBookingByRef, getErrorMessage, type PaymentMethod } from '../services/bookings';
import { formatLocation, getPropertyById, type Property } from '../services/properties';
import DateField, { toISODate } from '../components/DateField';
import Stepper from '../components/Stepper';
import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useMemo, useState } from 'react';
import * as WebBrowser from 'expo-web-browser';
import {
  ActivityIndicator,
  Alert,
  KeyboardAvoidingView,
  Platform,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const MS_PER_DAY = 1000 * 60 * 60 * 24;

export default function BookingSummaryScreen() {
  const { propertyId } = useLocalSearchParams<{ propertyId: string }>();
  const router = useRouter();
  const { t } = useI18n();
  const { user, isAuthenticated, isLoading: authLoading } = useAuth();
  const [property, setProperty] = useState<Property | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [checkIn, setCheckIn] = useState<Date | null>(null);
  const [checkOut, setCheckOut] = useState<Date | null>(null);
  const [adults, setAdults] = useState(1);
  const [children, setChildren] = useState(0);
  const [selectedRoomId, setSelectedRoomId] = useState<string | null>(null);
  const [paymentMethod, setPaymentMethod] = useState<PaymentMethod>('CASH');
  const [submitting, setSubmitting] = useState(false);

  useEffect(() => {
    getPropertyById(propertyId)
      .then((p) => {
        setProperty(p);
        if (p.rooms?.length) setSelectedRoomId(p.rooms[0].id);
      })
      .catch(() => {})
      .finally(() => setIsLoading(false));
  }, [propertyId]);

  const selectedRoom = property?.rooms?.find((r) => r.id === selectedRoomId) ?? null;
  const nights = checkIn && checkOut ? Math.round((checkOut.getTime() - checkIn.getTime()) / MS_PER_DAY) : 0;
  const total = useMemo(
    () => (selectedRoom && nights > 0 ? selectedRoom.ratePerNight * nights : 0),
    [selectedRoom, nights],
  );

  async function handleBook() {
    if (!checkIn || !checkOut) {
      Alert.alert(t.error, t.booking_fill_dates);
      return;
    }
    if (nights <= 0) {
      Alert.alert(t.error, t.checkout_after_checkin_required);
      return;
    }
    if (!selectedRoomId || !selectedRoom) {
      Alert.alert(t.error, t.no_rooms_available);
      return;
    }
    if (adults > selectedRoom.maxAdults || children > selectedRoom.maxChildren) {
      Alert.alert(t.error, t.guests_exceed_capacity);
      return;
    }
    if (!user) {
      Alert.alert(t.error, t.sign_in_to_book_msg);
      return;
    }
    setSubmitting(true);
    try {
      const booking = await createBooking({
        userId: Number(user.id),
        propertyId: Number(propertyId),
        roomId: Number(selectedRoomId),
        numberOfAdults: adults,
        numberOfChildren: children,
        checkInDate: toISODate(checkIn),
        checkOutDate: toISODate(checkOut),
        paymentMethod,
      });

      // CASH bookings come back already CONFIRMED with no paymentLink.
      // STRIPE/ETH_SWITCH come back PENDING with a paymentLink already
      // generated by the create call itself — no separate checkout step
      // needed for a fresh booking.
      if (booking.paymentLink) {
        await WebBrowser.openBrowserAsync(booking.paymentLink);
        const refreshed = await getBookingByRef(booking.reference).catch(() => booking);
        router.replace({ pathname: '/booking-details/[ref]', params: { ref: refreshed.reference } });
      } else {
        router.replace({ pathname: '/booking-details/[ref]', params: { ref: booking.reference } });
      }
    } catch (err: any) {
      Alert.alert(t.error, getErrorMessage(err, 'Booking failed'));
    } finally {
      setSubmitting(false);
    }
  }

  if (isLoading || authLoading) {
    return (
      <View style={styles.center}>
        <ActivityIndicator size="large" color={COLORS.primary} />
      </View>
    );
  }

  if (!isAuthenticated) {
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: COLORS.background }}>
        <View style={styles.topBar}>
          <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
            <Ionicons name="arrow-back" size={20} color={COLORS.textPrimary} />
          </TouchableOpacity>
          <Text style={styles.topTitle}>{t.booking_summary}</Text>
          <View style={{ width: 38 }} />
        </View>
        <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 32 }}>
          <View style={{ width: 72, height: 72, borderRadius: 36, backgroundColor: COLORS.primaryLight, justifyContent: 'center', alignItems: 'center', marginBottom: 20 }}>
            <Ionicons name="lock-closed-outline" size={32} color={COLORS.primary} />
          </View>
          <Text style={{ fontSize: 14, color: COLORS.textSecondary, textAlign: 'center', marginBottom: 24, lineHeight: 20 }}>
            {t.sign_in_to_book_msg}
          </Text>
          <TouchableOpacity
            style={{ backgroundColor: COLORS.primary, borderRadius: RADIUS.full, paddingVertical: 14, paddingHorizontal: 40 }}
            onPress={() => router.push({ pathname: '/(auth)/sign-in', params: { propertyId } })}
          >
            <Text style={{ color: '#fff', fontWeight: '700', fontSize: 15 }}>{t.sign_in}</Text>
          </TouchableOpacity>
        </View>
      </SafeAreaView>
    );
  }

  return (
    <KeyboardAvoidingView
      style={{ flex: 1, backgroundColor: COLORS.background }}
      behavior={Platform.OS === 'ios' ? 'padding' : undefined}
    >
      <SafeAreaView style={{ flex: 1 }}>
        <View style={styles.topBar}>
          <TouchableOpacity style={styles.backBtn} onPress={() => router.back()}>
            <Ionicons name="arrow-back" size={20} color={COLORS.textPrimary} />
          </TouchableOpacity>
          <Text style={styles.topTitle}>{t.booking_summary}</Text>
          <View style={{ width: 38 }} />
        </View>

        <ScrollView contentContainerStyle={styles.body}>
          {property && (
            <View style={styles.propertyCard}>
              <View style={styles.propertyCardInner}>
                <Text style={styles.propName}>{property.name}</Text>
                <View style={styles.propLocRow}>
                  <Ionicons name="location-outline" size={12} color={COLORS.primary} />
                  <Text style={styles.propLoc}>{formatLocation(property)}</Text>
                </View>
              </View>
              <View style={styles.propPriceCol}>
                <Text style={styles.propPriceAmt}>
                  {property.currency} {property.pricePerNight.toLocaleString()}
                </Text>
                <Text style={styles.propPriceNight}>{t.per_night}</Text>
              </View>
            </View>
          )}

          {property && property.rooms && property.rooms.length > 0 ? (
            <View style={styles.roomSection}>
              <Text style={styles.sectionLabel}>{t.select_room}</Text>
              {property.rooms.map((room) => {
                const selected = room.id === selectedRoomId;
                return (
                  <TouchableOpacity
                    key={room.id}
                    style={[styles.roomOption, selected && styles.roomOptionSelected]}
                    onPress={() => setSelectedRoomId(room.id)}
                    activeOpacity={0.8}
                  >
                    <View style={{ flex: 1 }}>
                      <Text style={styles.roomName}>{room.name}</Text>
                      <Text style={styles.roomCapacity}>
                        {room.maxAdults + room.maxChildren} {t.guests}
                      </Text>
                    </View>
                    <Text style={styles.roomRate}>
                      {property.currency} {room.ratePerNight.toLocaleString()}
                    </Text>
                    <Ionicons
                      name={selected ? 'radio-button-on' : 'radio-button-off'}
                      size={18}
                      color={selected ? COLORS.primary : COLORS.textMuted}
                      style={{ marginLeft: 10 }}
                    />
                  </TouchableOpacity>
                );
              })}
            </View>
          ) : property ? (
            <Text style={styles.noRoomsText}>{t.no_rooms_available}</Text>
          ) : null}

          <View style={styles.dateRow}>
            <DateField label={t.check_in} icon="log-in-outline" value={checkIn} onChange={setCheckIn} minimumDate={new Date()} />
            <DateField label={t.check_out} icon="log-out-outline" value={checkOut} onChange={setCheckOut} minimumDate={checkIn ?? new Date()} />
          </View>

          <View style={styles.guestsCard}>
            <Stepper label={t.adults} value={adults} onChange={setAdults} min={1} max={selectedRoom?.maxAdults ?? 10} />
            <Stepper label={t.children} value={children} onChange={setChildren} min={0} max={selectedRoom?.maxChildren ?? 10} />
          </View>

          <Text style={styles.sectionLabel}>{t.choose_payment_method}</Text>
          <TouchableOpacity
            style={[styles.paymentOption, paymentMethod === 'CASH' && styles.paymentOptionSelected]}
            onPress={() => setPaymentMethod('CASH')}
            activeOpacity={0.85}
          >
            <View style={styles.paymentIconWrap}>
              <Ionicons name="cash-outline" size={20} color={COLORS.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.paymentTitle}>{t.pay_at_property}</Text>
              <Text style={styles.paymentSub}>{t.pay_at_property_sub}</Text>
            </View>
            <Ionicons
              name={paymentMethod === 'CASH' ? 'radio-button-on' : 'radio-button-off'}
              size={18}
              color={paymentMethod === 'CASH' ? COLORS.primary : COLORS.textMuted}
            />
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.paymentOption, paymentMethod === 'STRIPE' && styles.paymentOptionSelected]}
            onPress={() => setPaymentMethod('STRIPE')}
            activeOpacity={0.85}
          >
            <View style={styles.paymentIconWrap}>
              <Ionicons name="card-outline" size={20} color={COLORS.primary} />
            </View>
            <View style={{ flex: 1 }}>
              <Text style={styles.paymentTitle}>{t.pay_with_card}</Text>
              <Text style={styles.paymentSub}>{t.pay_with_card_sub}</Text>
            </View>
            <Ionicons
              name={paymentMethod === 'STRIPE' ? 'radio-button-on' : 'radio-button-off'}
              size={18}
              color={paymentMethod === 'STRIPE' ? COLORS.primary : COLORS.textMuted}
            />
          </TouchableOpacity>

          {nights > 0 && selectedRoom && property && (
            <View style={styles.totalCard}>
              <View style={styles.totalRow}>
                <Text style={styles.totalLabel}>{nights} {t.nights} × {property.currency} {selectedRoom.ratePerNight.toLocaleString()}</Text>
                <Text style={styles.totalValue}>{property.currency} {total.toLocaleString()}</Text>
              </View>
              <View style={[styles.totalRow, { marginTop: 8 }]}>
                <Text style={styles.totalLabelBold}>{t.total}</Text>
                <Text style={styles.totalValueBold}>{property.currency} {total.toLocaleString()}</Text>
              </View>
            </View>
          )}

          <TouchableOpacity
            style={[styles.btn, submitting && styles.btnDisabled]}
            onPress={handleBook}
            disabled={submitting}
            activeOpacity={0.85}
          >
            <Text style={styles.btnText}>
              {submitting ? t.loading : t.confirm_booking}
            </Text>
          </TouchableOpacity>
        </ScrollView>
      </SafeAreaView>
    </KeyboardAvoidingView>
  );
}

const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: COLORS.background },

  topBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.card,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.background,
    justifyContent: 'center',
    alignItems: 'center',
  },
  topTitle: { fontWeight: '700', fontSize: 17, color: COLORS.textPrimary },

  body: { padding: 20, gap: 4 },

  propertyCard: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.lg,
    padding: 16,
    marginBottom: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    ...SHADOW.sm,
  },
  propertyCardInner: { flex: 1, marginRight: 12 },
  propName: { fontWeight: '700', fontSize: 15, color: COLORS.textPrimary, marginBottom: 4 },
  propLocRow: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  propLoc: { color: COLORS.textSecondary, fontSize: 12 },
  propPriceCol: { alignItems: 'flex-end' },
  propPriceAmt: { fontWeight: '800', fontSize: 15, color: COLORS.primary },
  propPriceNight: { fontSize: 11, color: COLORS.textSecondary },

  roomSection: { marginBottom: 16 },
  sectionLabel: { fontSize: 13, fontWeight: '600', color: COLORS.textPrimary, marginBottom: 8 },
  roomOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.lg,
    borderWidth: 1,
    borderColor: COLORS.border,
    padding: 12,
    marginBottom: 8,
  },
  roomOptionSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primaryLight },
  roomName: { fontSize: 14, fontWeight: '600', color: COLORS.textPrimary },
  roomCapacity: { fontSize: 12, color: COLORS.textSecondary, marginTop: 2 },
  roomRate: { fontSize: 13, fontWeight: '700', color: COLORS.primary },
  noRoomsText: { color: COLORS.textSecondary, fontSize: 13, marginBottom: 16 },

  dateRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },

  guestsCard: {
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.lg,
    paddingHorizontal: 14,
    marginBottom: 20,
    ...SHADOW.sm,
  },

  paymentOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: COLORS.card,
    borderRadius: RADIUS.lg,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    padding: 14,
    marginBottom: 10,
  },
  paymentOptionSelected: { borderColor: COLORS.primary, backgroundColor: COLORS.primaryLight },
  paymentIconWrap: {
    width: 38,
    height: 38,
    borderRadius: RADIUS.full,
    backgroundColor: COLORS.card,
    justifyContent: 'center',
    alignItems: 'center',
  },
  paymentTitle: { fontSize: 13, fontWeight: '700', color: COLORS.textPrimary, marginBottom: 2 },
  paymentSub: { fontSize: 11, color: COLORS.textSecondary },

  totalCard: {
    backgroundColor: COLORS.backgroundAlt,
    borderRadius: RADIUS.lg,
    padding: 14,
    marginBottom: 16,
    marginTop: 8,
  },
  totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  totalLabel: { fontSize: 12, color: COLORS.textSecondary },
  totalValue: { fontSize: 12, color: COLORS.textSecondary },
  totalLabelBold: { fontSize: 14, fontWeight: '700', color: COLORS.textPrimary },
  totalValueBold: { fontSize: 16, fontWeight: '800', color: COLORS.primary },

  btn: {
    backgroundColor: COLORS.primary,
    height: 54,
    borderRadius: RADIUS.lg,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
    ...SHADOW.sm,
  },
  btnDisabled: { opacity: 0.6 },
  btnText: { color: '#fff', fontWeight: '700', fontSize: 16 },
});
